// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKwH8cMsEkN4whlDykp7JCGNMHtcZq7_o',
    appId: '1:20753629784:web:c0ae87d33c30b3dae2c02d',
    messagingSenderId: '20753629784',
    projectId: 'tictactoe-multiplayer-23',
    authDomain: 'tictactoe-multiplayer-23.firebaseapp.com',
    storageBucket: 'tictactoe-multiplayer-23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyljkiuLyFZT6kDW3_Aw81KG-YDht54IE',
    appId: '1:20753629784:android:b24f2b921409c11be2c02d',
    messagingSenderId: '20753629784',
    projectId: 'tictactoe-multiplayer-23',
    storageBucket: 'tictactoe-multiplayer-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2nrbtNFaCdUzPbBUtXi0uO5AeEdIie0w',
    appId: '1:20753629784:ios:1352a0697f24eed0e2c02d',
    messagingSenderId: '20753629784',
    projectId: 'tictactoe-multiplayer-23',
    storageBucket: 'tictactoe-multiplayer-23.appspot.com',
    androidClientId: '20753629784-13mi8kfl9ost16m0rhfv1ml5otca0omd.apps.googleusercontent.com',
    iosClientId: '20753629784-jtfivjraav3hfk1lkc3iohdavke90q8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.netwealthVjti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2nrbtNFaCdUzPbBUtXi0uO5AeEdIie0w',
    appId: '1:20753629784:ios:1352a0697f24eed0e2c02d',
    messagingSenderId: '20753629784',
    projectId: 'tictactoe-multiplayer-23',
    storageBucket: 'tictactoe-multiplayer-23.appspot.com',
    androidClientId: '20753629784-13mi8kfl9ost16m0rhfv1ml5otca0omd.apps.googleusercontent.com',
    iosClientId: '20753629784-jtfivjraav3hfk1lkc3iohdavke90q8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.netwealthVjti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKwH8cMsEkN4whlDykp7JCGNMHtcZq7_o',
    appId: '1:20753629784:web:29937b6a68d46ee7e2c02d',
    messagingSenderId: '20753629784',
    projectId: 'tictactoe-multiplayer-23',
    authDomain: 'tictactoe-multiplayer-23.firebaseapp.com',
    storageBucket: 'tictactoe-multiplayer-23.appspot.com',
  );
}
